#!/bin/sh
#Rapid VM builder - http://safrm.net/projects/rvmb
#author: Miroslav Safr <miroslav.safr@gmail.com> 
VERSION=NA
VERSION_DATE=NA

TARGET_DIR=/etc/rvmb/targets
TARGET_FILE=
BASENAME=`basename $0`
SHARE_DIR=./share
MEMORY=1024
TS=$(date +%Y_%m_%d__%H_%M)

#helpers
alias echo="/bin/echo -e"
log()  { printf  "%b\n" "$*"; }
debug(){ [ ${DEBUG_FLAG:-0} -eq 0 ] || echo "Running($#): $*"; }
verbose(){ [ ${VERBOSE_FLAG:-0} -eq 0 ] || echo "$*"; }
fail() { log "\nERROR: $*\n" ; exit 1 ; }

usage() {
    echo "$BASENAME ${VERSION} - Rapid VM builder for qemu-kvm"
    echo " http://safrm.net/projects/rvmo/"
    echo "Usage:$BASENAME [COMMAND] [TARGET-FILE] [OPTIONS]..."
    echo " COMMAND ............................ specify step execution "
    echo "  list-targets list-images show-target "
    echo "  prepare-host create-disk download-iso run-live-iso install-image "
    echo "  start stop status status-all kill-all"
    echo "  backup-image mount-image umount-image chroot-image"
    echo "  connect-ssh connect-vnc"
    echo " OPTIONS: "
    echo " -h, --help ......................... shows command line help"
    echo " -v, --verbose ...................... prints more output"
    echo " -d, --debug ........................ enable debug"
    echo " -c, --clone <number> ............... cloning increment number (adds postfix, increases ports etc.)"
    echo " -m, --memory <kB> .................. uses specific VM memory amount"
    echo " -u, --user <VM-user> ............... uses own VM user (default user)"
    echo " -vnc ............................... enable vnc on display (:1 + clone)"
    echo " -ng, --nographic ................... disable graphical output"
    echo " -V, --version  ..................... prints version of the scripts"
	echo " TARGET-FILE ........................ target config file name or full path,"
    echo "                                      targets files are in /etc/rvmb/targets or ./targets"
    echo " "
}

rvmb_status_all()
{
	ls -1 ./*-running 2> /dev/null
	echo
	ps -AF | grep [q]emu	
}

rvmb_kill_all()
{
	debug "rvmb_kill_all"	
	rm -fr ./*-running 
	echo
	QEMUPIDS=`pgrep [q]emu` 
	if [ -n "$QEMUPIDS" ]; then
		echo "killing: $QEMUPIDS"
		for QEMUPID in "${QEMUPIDS}"
		do
				debug "kill $QEMUPID"
			    kill $QEMUPID
		done
	else 	
		echo "no qemu processes running"
	fi
}

#cmdline parsing 
while [ $# -gt 0 ]; do
  case "$1" in
    prepare-host | create-disk | download-iso | run-live-iso | install-image | start | stop | status | connect-ssh | connect-vnc | backup-image | mount-image | umount-image | chroot-image)
        [ -z "$DEFAULT_CMD" ] || fail "Only one command can be run at the time"
	DEFAULT_CMD=$1 ;;
    list-targets )
		if [ -e ./targets ]; then
			echo "\033[01;34m`pwd`/targets:\033[33m" ; ls -1 ./targets 2> /dev/null ;
			echo "\033[0m"
		fi
		echo "\033[01;34m$TARGET_DIR:\033[0m"; ls -1 $TARGET_DIR ; exit 0;;
	list-images )
		ls -1 *.raw *.img *.qcow 2>/dev/null ; exit 0;;
	show-target) VERBOSE_FLAG=1 ; DEFAULT_CMD=$1 ;;
    status-all) rvmb_status_all ; exit ;;
    kill-all) rvmb_kill_all ; exit ;;
    -h | --help) 
        usage ; exit 0 ;;
    -vnc  )	
        VNC_FLAG=-vnc ;;
     -ng|--nographic) 
        NOGRAPHIC_FLAG=-nographic ;;
     -v|--verbose) 
        VERBOSE_FLAG=1 ;;
    -d | --debug) 
        DEBUG_FLAG=1 ;;
    -c | --clone ) shift;
        CLONE_NO=$1 
		if [ $CLONE_NO -ne 0 -o $CLONE_NO -eq 0 2> /dev/null ]; then
			debug "integer CLONE_NO=$CLONE_NO ok"
		else
			fail "$CLONE_NO is not valid number" 
		fi ;;
    -m | --memory ) shift;
        MEMORY=$1 
		if [ $MEMORY -ne 0 -o $MEMORY -eq 0 2> /dev/null ]; then
			debug "integer MEMORY=$MEMORY ok"
		else
			fail "$MEMORY is not valid number" 
		fi ;;
    -u | --user ) shift;
        VMUSER=$1 ;;
    * )      
		[ -n "$TARGET_FILE" ] && fail "Target can be only one ($TARGET_FILE)"
        TARGET_FILE=$1 
		if [ $(echo $TARGET_FILE | head -c1) = '/' -a -f $TARGET_FILE ]; then 
			:
		#local file first
		elif [ -f ./targets/$TARGET_FILE ]; then
	        TARGET_FILE=./targets/$TARGET_FILE
		#targets file second
		elif [ -f $TARGET_DIR/$TARGET_FILE ]; then 
			TARGET_FILE=$TARGET_DIR/$TARGET_FILE
		else 
			fail "Not valid target name: $TARGET_FILE, try rvmb list-targets" 
		fi ;;
  esac
  shift
done

#read configuration
[ -f "$TARGET_FILE" ] && debug "file exists $TARGET_FILE" || fail "Target configuration file $TARGET_FILE does not exist"
. $TARGET_FILE
DISK_NAME=`basename $TARGET_FILE`
echo "Using target configuration from $TARGET_FILE for $NAME"
verbose "`cat $TARGET_FILE` \n" 

#fixes for clonned environments
BASE_DISK_NAME=$DISK_NAME
if [ -n "$CLONE_NO" ]; then
	DISK_NAME=$DISK_NAME$CLONE_NO
    HOST_SSH_PORT=$(($HOST_SSH_PORT + $CLONE_NO)) ;
	verbose "CLONNED MODIFICATIONS:\nDISK_NAME=$DISK_NAME\nHOST_SSH_PORT=$HOST_SSH_PORT"
fi
MONITOR_FILE=./$DISK_NAME-running
verbose "MONITOR_FILE=$MONITOR_FILE"
if [ -n "$VNC_FLAG" ]; then
	VNC_PORT=1
	[ -n "$CLONE_NO" ] && VNC_PORT=$(($VNC_PORT + $CLONE_NO)) ;
	VNC_PORT=:$VNC_PORT
	echo "VNC OPTIONS: $VNC_FLAG $VNC_PORT"
fi

rvmb_show_target()
{
	exit 0;
}

rvmb_installation()
{
	debug "rvmb_installation:"
	rvmb_prepare
	rvmb_create_disk
	#we run it straight
	if [ -e $BASE_DISK_NAME.$DISK_FORMAT_EXT -a -n $CLONE_NO ]; then
		rvmb_start_vm
	else
		rvmb_install_image
	fi
}

rvmb_run_live_iso() 
{
	debug "rvmb_run_live_iso:"
	rvmb_prepare
	rvmb_download_iso
	echo "Runing live iso $ISO_FILE_LOCAL"
	qemu-system-x86_64 -name "live $ISO_FILE_LOCAL" $VNC_FLAG $VNC_PORT $NOGRAPHIC_FLAG -m $MEMORY -boot d -cdrom $ISO_FILE_LOCAL -enable-kvm -smp 2 -net nic,model=virtio -net user,net=192.168.101.0/24,hostfwd=tcp::$HOST_SSH_PORT-:22 -fsdev  local,security_model=none,id=fsdev0,path=$SHARE_DIR -device virtio-9p-pci,id=fs0,fsdev=fsdev0,mount_tag=hostshare -monitor unix:$MONITOR_FILE,server,nowait
}

#check and install host 
rvmb_prepare()
{
	debug "rvmb_prepare:"
	REQUIRED_PACKAGES="qemu-system-x86 qemu-utils kvm "
	dpkg-query -l $REQUIRED_PACKAGES > /dev/null
	if [ $? != 0 ]; then
		sudo apt-get install -y $REQUIRED_PACKAGES  || fail "Failed to install required packages"
	fi
}

rvmb_create_disk()
{
	debug "rvmb_create_disk:"
	if [ -e $DISK_NAME.$DISK_FORMAT_EXT ]; then
		echo "Disk $DISK_NAME.$DISK_FORMAT_EXT exists, Do you want to overwrite it Y/n ?"
		while true
	    do
    	    KEY=$(bash -c 'read -p " Do you want to continue (d=delete dir and continue)? [y/n/d] " -n 1 ans;echo "$ans"')
    	    echo ""
    	    case $KEY in
    		    y|Y|YES|yes|Yes) break ;;
    		    n|N|no|NO|No|*)
        		    echo "Aborting - you entered $KEY" ;  exit 1 ;;      
		    esac
	    done
	fi
	#clone or create
	if [ -e $BASE_DISK_NAME.$DISK_FORMAT_EXT -a -n $CLONE_NO ]; then
		verbose "Copying image: $BASE_DISK_NAME.$DISK_FORMAT_EXT to $DISK_NAME.$DISK_FORMAT_EXT $DISK_SIZE"
		cp -f $BASE_DISK_NAME.$DISK_FORMAT_EXT $DISK_NAME.$DISK_FORMAT_EXT 
	else
		verbose "Creating image: $DISK_NAME.$DISK_FORMAT_EXT $DISK_SIZE"
		qemu-img create -f $DISK_FORMAT_EXT $DISK_NAME.$DISK_FORMAT_EXT $DISK_SIZE || fail "Image creation failed"
	fi
}

rvmb_download_iso()
{
debug "rvmb_download_iso: Iso image url: $ISO_URL"
#-q=no output, -i=insensitive, -e=regexp
if echo $ISO_URL | grep -q -i -e "^\(ftp\|http\|https\):.*" ; then
	wget -N $ISO_URL || fail "Iso file download failed "
    ISO_FILE_LOCAL="${ISO_URL##*/}"
else
	if [ -f $ISO_URL ]; then	
		debug "Local file $ISO_URL ready"
		ISO_FILE_LOCAL="$ISO_URL"
	else	
		fail "Local file $ISO_URL does not exist"
	fi
fi

}

rvmb_install_image()
{
	debug "rvmb_install_image:"
	rvmb_download_iso
	debug "image:./$DISK_NAME.$DISK_FORMAT_EXT iso:	$ISO_FILE_LOCAL"
	[ -e ./$DISK_NAME.$DISK_FORMAT_EXT ] || fail "Image ./$DISK_NAME.$DISK_FORMAT_EXT does not exist"
	[ -e $ISO_FILE_LOCAL ] || fail "Iso file $ISO_FILE_LOCAL does not exist "
	[ -e $SHARE_DIR ] || mkdir -p $SHARE_DIR

	qemu-system-x86_64 -name "$DISK_NAME install" $VNC_FLAG $VNC_PORT $NOGRAPHIC_FLAG -m $MEMORY -boot d -cdrom $ISO_FILE_LOCAL -enable-kvm -smp 2 -net nic,model=virtio -net user,net=192.168.101.0/24,hostfwd=tcp::$HOST_SSH_PORT-:22 -drive file=./$DISK_NAME.$DISK_FORMAT_EXT,if=virtio -fsdev  local,security_model=none,id=fsdev0,path=$SHARE_DIR -device virtio-9p-pci,id=fs0,fsdev=fsdev0,mount_tag=hostshare -monitor unix:$MONITOR_FILE,server,nowait

}

#run ready VM
rvmb_start_vm() 
{
	debug "rvmb_start_vm"
	[ -e ./$DISK_NAME.$DISK_FORMAT_EXT ] || fail "Image ./$DISK_NAME.$DISK_FORMAT_EXT does not exist"
	#run
	qemu-system-x86_64 -name $DISK_NAME $VNC_FLAG $VNC_PORT $NOGRAPHIC_FLAG -m $MEMORY -hda $DISK_NAME.$DISK_FORMAT_EXT -boot c -enable-kvm -smp 2 -net nic,model=virtio -net user,net=192.168.101.0/24,hostfwd=tcp::$HOST_SSH_PORT-:22 -drive file=$DISK_NAME.$DISK_FORMAT_EXT,if=virtio -fsdev  local,security_model=none,id=fsdev0,path=$SHARE_DIR -device virtio-9p-pci,id=fs0,fsdev=fsdev0,mount_tag=hostshare -monitor unix:$MONITOR_FILE,server,nowait &

	#sudo mount -t 9p -o trans=virtio,version=9p2000.L,posixacl,cache=loose hostshare /share
}

rvmb_stop_vm()
{
	debug "rvmb_stop_vm"
	#using qemu
	debug "Stopping: $MONITOR_FILE"
	echo 'system_powerdown' | socat - UNIX-CONNECT:$MONITOR_FILE
	sleep 5;	
	echo 'quit' | socat - UNIX-CONNECT:$MONITOR_FILE	
	if [ -n "$MONITOR_FILE" -a -e $MONITOR_FILE ]; then
		echo " monitor file exits: $MONITOR_FILE, removing file.."
		rm "$MONITOR_FILE"
	fi
}


rvmb_status()
{
	debug "rvmb_status"
	RUNNING=0
	if [ -e $MONITOR_FILE ]; then
		verbose " monitor file exits: $MONITOR_FILE"
		RUNNING=1
		echo 'info status ' | socat - UNIX-CONNECT:$MONITOR_FILE	
	else
		verbose " monitor file does not exits: $MONITOR_FILE"
		RUNNING_PROBLEM="monitor file does not exits "
	fi
	if [ $(pgrep -f $DISK_NAME.$DISK_FORMAT_EXT) ]; then
		verbose " image $DISK_NAME.$DISK_FORMAT_EXT is running"
		RUNNING=1
	else
		verbose " image $DISK_NAME.$DISK_FORMAT_EXT is not running"
		RUNNING_PROBLEM="${RUNNING_PROBLEM}process with image is not running"
	fi
	if [ $RUNNING -eq 1 ]; then
		echo "running"
		if [ -n "$RUNNING_PROBLEM" ]; then
			echo "$RUNNING_PROBLEM"
			exit 1;
		fi
	else
		echo "not running"
	fi
}


rvmb_connect_vm_ssh()
{
	verbose "VMUSER:$VMUSER PORT:$HOST_SSH_PORT"
	ssh -X ${VMUSER:-user}@localhost -p $HOST_SSH_PORT 
}
rvmb_connect_vm_vnc()
{
	vncviewer -via $USER@localhost  localhost$VNC_PORT
}

rvmb_backup_image()
{
    [ -e ./$DISK_NAME.$DISK_FORMAT_EXT ] || fail "Image ./$DISK_NAME.$DISK_FORMAT_EXT does not exist"
	tar cvjf ./$DISK_NAME.$DISK_FORMAT_EXT_$TS.tar.bz2 ./$DISK_NAME.$DISK_FORMAT_EXT
}

rvmb_mount_image()
{
	MOUNT_DIR=./$DISK_NAME.$DISK_FORMAT_EXT-mount
	MOUNTED=`mount |  grep "$DISK_NAME.$DISK_FORMAT_EXT-mount "`
	if [ -z "$MOUNTED" ]; then
		[ -d $MOUNT_DIR ] || mkdir $MOUNT_DIR
		sudo mount -o loop,offset=$((512*2048)) ./$DISK_NAME.$DISK_FORMAT_EXT $MOUNT_DIR -t ext4 && echo "mounted ok"
	else 
		verbose "already mounted to $DISK_NAME.$DISK_FORMAT_EXT-mount"
	fi
}

rvmb_umount_image()
{
	MOUNT_DIR=./$DISK_NAME.$DISK_FORMAT_EXT-mount
	MOUNTED=`mount |  grep "$MOUNT_DIR "`
	if [ -n "$MOUNTED" ]; then
		MOUNTEDPROC=`mount |  grep "$MOUNT_DIR/proc "`
		if [ -n "$MOUNTEDPROC" ]; then
			sudo umount $MOUNT_DIR/proc && echo "proc unmounted ok"	
			sleep 1
		fi
		sudo umount $MOUNT_DIR && echo "unmounted image ok"
	else
		echo "Image:./$DISK_NAME.$DISK_FORMAT_EXT is not mounted"
	fi
}


rvmb_chroot_image()
{
	rvmb_mount_image
	sudo mount --bind /proc $MOUNT_DIR/proc
	sudo chroot $MOUNT_DIR su -c sh root
}

case $DEFAULT_CMD in
  show-target) rvmb_show_target ;;
  prepare-host) rvmb_prepare ;;
  create-disk) rvmb_create_disk ;;
  download-iso) rvmb_download_iso ;;
  run-live-iso) rvmb_run_live_iso ;;
  install-image) rvmb_install_image ;;
  start) rvmb_start_vm ;;
  status) rvmb_status ;;
  stop) rvmb_stop_vm ;;
  connect-ssh) rvmb_connect_vm_ssh ;;
  connect-vnc) rvmb_connect_vm_vnc ;;
  mount-image) rvmb_mount_image ;;
  umount-image) rvmb_umount_image ;;
  backup-image) rvmb_backup_image ;;
  chroot-image) rvmb_chroot_image ;;
  #automatic target: empty=install, ok=start, running=connect-ssh
  *) 
	if [ ! -e $DISK_NAME.$DISK_FORMAT_EXT ]; then
		debug "$DISK_NAME.$DISK_FORMAT_EXT does not exist"
		rvmb_installation ;
	else
		debug "$DISK_NAME.$DISK_FORMAT_EXT exists"
		# check that runs?
		rvmb_start_vm ;
	fi
esac

